//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport
    {
        public int SportID { get; set; }
        public string SportTitle { get; set; }
        public string Description { get; set; }
    }
}
