// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportApplication.Data;

namespace SportApplication.Migrations
{
    [DbContext(typeof(SportContext))]
    partial class SportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SportApplication.Models.Contestant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Contestants");
                });

            modelBuilder.Entity("SportApplication.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContestantID")
                        .HasColumnType("int");

                    b.Property<int>("SportID")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("ContestantID");

                    b.HasIndex("SportID");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("SportApplication.Models.Sport", b =>
                {
                    b.Property<int>("SportID")
                        .HasColumnType("int");

                    b.Property<int?>("ContestantID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportID");

                    b.HasIndex("ContestantID");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("SportApplication.Models.Enrollment", b =>
                {
                    b.HasOne("SportApplication.Models.Contestant", "Contestant")
                        .WithMany()
                        .HasForeignKey("ContestantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportApplication.Models.Sport", "Sport")
                        .WithMany("Enrollments")
                        .HasForeignKey("SportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportApplication.Models.Sport", b =>
                {
                    b.HasOne("SportApplication.Models.Contestant", null)
                        .WithMany("Sports")
                        .HasForeignKey("ContestantID");
                });
#pragma warning restore 612, 618
        }
    }
}
